# .github/workflows/railway-deploy.yml
name: .NET 9 CI/CD → Railway

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build in Release
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  deploy:
    name: Deploy to Railway
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Railway login
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --apiKey $RAILWAY_TOKEN

      - name: Link project
        run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Build, push & deploy
        run: railway up --detach
